# springcloud集成开始环境部署包括了configserver和eureka等
version: "3.3"
services:

  eurekaserver1:
    build: ./eureka-server
    restart: on-failure
    ports:
      - "6761:6761"
      - "6762:6762"
    networks:
      - dev
    environment:
      - PORT=6761
      - BG_PORT=6762
      - NAME=eureka1
      - URL=http://eureka2:6761/eureka #集群地址配置

  eurekaserver2:
    build: ./eureka-server
    restart: on-failure
    ports:
      - "5761:5761"
      - "5762:5762"
    networks:
      - dev
    environment:
      - PORT=5761
      - BG_PORT=5762
      - NAME=eureka2
      - URL=http://eureka1:6761/eureka #集群地址配置

  configserver:
    build: ./config-server
    ports:
      - "6200:6200"
      - "6201:6201"
    networks:
      - dev
    depends_on:
      - eurekaserver1 #依赖服务
      - eurekaserver2
    environment:
      - PORT=6200
      - BG_PORT=6201

networks:
  dev:
    driver: bridge

